require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndexCardsController do

  # This should return the minimal set of attributes required to create a valid
  # IndexCard. As you add validations to IndexCard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndexCardsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all index_cards as @index_cards" do
      index_card = IndexCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:index_cards).should eq([index_card])
    end
  end

  describe "GET show" do
    it "assigns the requested index_card as @index_card" do
      index_card = IndexCard.create! valid_attributes
      get :show, {:id => index_card.to_param}, valid_session
      assigns(:index_card).should eq(index_card)
    end
  end

  describe "GET new" do
    it "assigns a new index_card as @index_card" do
      get :new, {}, valid_session
      assigns(:index_card).should be_a_new(IndexCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested index_card as @index_card" do
      index_card = IndexCard.create! valid_attributes
      get :edit, {:id => index_card.to_param}, valid_session
      assigns(:index_card).should eq(index_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IndexCard" do
        expect {
          post :create, {:index_card => valid_attributes}, valid_session
        }.to change(IndexCard, :count).by(1)
      end

      it "assigns a newly created index_card as @index_card" do
        post :create, {:index_card => valid_attributes}, valid_session
        assigns(:index_card).should be_a(IndexCard)
        assigns(:index_card).should be_persisted
      end

      it "redirects to the created index_card" do
        post :create, {:index_card => valid_attributes}, valid_session
        response.should redirect_to(IndexCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved index_card as @index_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        IndexCard.any_instance.stub(:save).and_return(false)
        post :create, {:index_card => {}}, valid_session
        assigns(:index_card).should be_a_new(IndexCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IndexCard.any_instance.stub(:save).and_return(false)
        post :create, {:index_card => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested index_card" do
        index_card = IndexCard.create! valid_attributes
        # Assuming there are no other index_cards in the database, this
        # specifies that the IndexCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IndexCard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => index_card.to_param, :index_card => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested index_card as @index_card" do
        index_card = IndexCard.create! valid_attributes
        put :update, {:id => index_card.to_param, :index_card => valid_attributes}, valid_session
        assigns(:index_card).should eq(index_card)
      end

      it "redirects to the index_card" do
        index_card = IndexCard.create! valid_attributes
        put :update, {:id => index_card.to_param, :index_card => valid_attributes}, valid_session
        response.should redirect_to(index_card)
      end
    end

    describe "with invalid params" do
      it "assigns the index_card as @index_card" do
        index_card = IndexCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IndexCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => index_card.to_param, :index_card => {}}, valid_session
        assigns(:index_card).should eq(index_card)
      end

      it "re-renders the 'edit' template" do
        index_card = IndexCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IndexCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => index_card.to_param, :index_card => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested index_card" do
      index_card = IndexCard.create! valid_attributes
      expect {
        delete :destroy, {:id => index_card.to_param}, valid_session
      }.to change(IndexCard, :count).by(-1)
    end

    it "redirects to the index_cards list" do
      index_card = IndexCard.create! valid_attributes
      delete :destroy, {:id => index_card.to_param}, valid_session
      response.should redirect_to(index_cards_url)
    end
  end

end
